### ISSUE TITLE
[Component] TypeError: track(...) is not a function

### ISSUE THREAD

**Issue by geedys** [element-plus/element-plus#12865]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.3`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 113`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Link]()

### Steps to reproduce

使用2.3.4版本,升级vue3.3.3, vite 4.3.7后即出现该错误

### What is Expected?

不要报错

### What is actually happening?

runtime-core.esm-bundler.js:2939 Uncaught (in promise) TypeError: track(...) is not a function
    at Object.get (runtime-core.esm-bundler.js:2939:35)
    at drawer.vue:29:27
    at renderFnWithContext (runtime-core.esm-bundler.js:766:13)
    at renderSlot (runtime-core.esm-bundler.js:2823:53)
    at Proxy._sfc_render294 (focus-trap.vue:2:3)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5696:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5809:51)
    at setupRenderEffect (runtime-core.esm-bundler.js:5817:5)

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/4887904/d624dd4a-96c3-484c-8bdf-228432debc82)

**Comment by markthree** [comment]
@geedys the issue has been fixed 👉 [vuejs/core/pull/8358](https://github.com/vuejs/core/pull/8358)

Please update vue version 👉 [^3.3.4](https://github.com/vuejs/core/blob/main/CHANGELOG.md#334-2023-05-18)

**Comment by geedys** [comment]
> @geedys the issue has been fixed 👉 [vuejs/core/pull/8358](https://github.com/vuejs/core/pull/8358)
> 
> Please update vue version 👉 [^3.3.4](https://github.com/vuejs/core/blob/main/CHANGELOG.md#334-2023-05-18)

Thanks .
