### ISSUE TITLE
[Build] [All] Yarn+Vite build error

### ISSUE THREAD

**Issue by QuanQuan-CHO** [element-plus/element-plus#14068]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: `macOS 13.4.1 and Windows 10 both occur`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/QuanQuan-CHO/element-plus-yarn-vite-build-error)

### Steps to reproduce

```shell
> node --version
v18.17.1
> npm --version
9.6.7
> yarn --version
3.6.2
> yarn create vue@3.7.3
...
Vue.js - The Progressive JavaScript Framework

√ Project name: ... element-plus-yarn-vite-build-error
√ Add TypeScript? ... No
√ Add JSX Support? ... No
√ Add Vue Router for Single Page Application development? ... No
√ Add Pinia for state management? ... No
√ Add Vitest for Unit Testing? ... No
√ Add an End-to-End Testing Solution? » No
√ Add ESLint for code quality? ... No

Scaffolding project in ...

> cd element-plus-yarn-vite-build-error
> yarn
...
> yarn add element-plus@^2.3.9
...
> vim src/main.js #https://element-plus.org/en-US/guide/quickstart.html#full-import
import './assets/main.css'

import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'

const app = createApp(App)
app.use(ElementPlus)
app.mount('#app')
:wq

> yarn run build
vite v4.4.9 building for production...
✓ 18 modules transformed.
✓ built in 659ms
[vite]: Rollup failed to resolve import "@vue/shared" from "D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/__virtual__/element-plus-virtual-0357ab0aa5/0/cache/element-plus-npm-2.3.9-568b3b02ee-9b6e33392a.zip/node_modules/element-plus/es/components/autocomplete/src/autocomplete.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@vue/shared" from "D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/__virtual__/element-plus-virtual-0357ab0aa5/0/cache/element-plus-npm-2.3.9-568b3b02ee-9b6e33392a.zip/node_modules/element-plus/es/components/autocomplete/src/autocomplete.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/__virtual__/vite-virtual-3a23e8e43c/0/cache/vite-npm-4.4.9-e845c1bbf8-c511024cea.zip/node_modules/vite/dist/node/chunks/dep-df561101.js:48142:27)
    at onRollupWarning (file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/__virtual__/vite-virtual-3a23e8e43c/0/cache/vite-npm-4.4.9-e845c1bbf8-c511024cea.zip/node_modules/vite/dist/node/chunks/dep-df561101.js:48174:9)
    at onwarn (file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/__virtual__/vite-virtual-3a23e8e43c/0/cache/vite-npm-4.4.9-e845c1bbf8-c511024cea.zip/node_modules/vite/dist/node/chunks/dep-df561101.js:47902:13)
    at file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/cache/rollup-npm-3.28.1-f67720d1e1-1fcab0929c.zip/node_modules/rollup/dist/es/shared/node-entry.js:24194:13
    at Object.logger [as onLog] (file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/cache/rollup-npm-3.28.1-f67720d1e1-1fcab0929c.zip/node_modules/rollup/dist/es/shared/node-entry.js:25867:9)
    at ModuleLoader.handleInvalidResolvedId (file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/cache/rollup-npm-3.28.1-f67720d1e1-1fcab0929c.zip/node_modules/rollup/dist/es/shared/node-entry.js:24780:26)
    at file:///D:/vscode-projects/element-plus-yarn-vite-build-error/.yarn/cache/rollup-npm-3.28.1-f67720d1e1-1fcab0929c.zip/node_modules/rollup/dist/es/shared/node-entry.js:24740:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### What is Expected?

build success

### What is actually happening?

build error

### Additional comments

1. A very similar issue: https://github.com/element-plus/element-plus/issues/10731
2. Apparently, the build error is caused by the missing package "@vue/shared"
   We can solve the error with `yarn add @vue/shared`, but obviously, it isn't a good solution
3. If we change the package manager from **Yarn** to **npm** and re-execute the above steps, then the build will success
4. Environment:
   - Node.js v18.17.1
   - npm v9.6.7
   - Yarn v3.6.2
   - Vue v3.3.4
   - Vite v4.4.9
   - Element-Plus v2.3.9

**Comment by zhao1995chen** [comment]
Using yarn `v1.22.19` both install and build are successful. 
<img width="981" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/2cd0490f-025f-43bc-87ee-8da824f9d37b">

---

Redo the process after deleting node_modules.
Using yarn `v3.6.3` both install and build are successful. 
<img width="981" alt="image" src="https://github.com/element-plus/element-plus/assets/53460349/d6f60809-f013-4b80-8197-4f4522c1f089">

---

Could you please provide more details to reproduce the problem?
