### ISSUE TITLE
[Bug Report] Cannot read property 'row' of undefined paused on exception only during debug.

### ISSUE THREAD

**Issue by vadimt2** [element-plus/element-plus#1614]
* When i'm selecting an item and i'm on debug mode (Inspect F12)
It's showing me this message where is **paused on exception**:
Bug:
```
TypeError: Cannot read property 'row' of undefined
```
Scope is undefined as well.

```
Exception: TypeError: Cannot read property 'row' of undefined at eval (webpack-internal:///./node_modules/vue-loader-v16/dist/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/components/files-component/files-component.vue?vue&type=template&id=b5bf2a42:142:41) at Proxy.renderFnWithContext (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1603:21) at Proxy.render (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:142:249184) at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:851:44) at componentEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4406:34) at reactiveEffect (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:71:24) at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:276:36) at flushJobs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:503:17)
scope: undefined
this: undefined
```
*** If I will select an item without F12 inspector and then i will open the inspecor it will show no error.
and it will do the work like it should be, it's just annoying and make it harder to debug**

```
 <el-table v-if="!filesDialog"
      ref="propFileTreeTable"
        :data="documents"
        row-key="uid"
        height="height: 100%"
        style="height: 100% !important; position: absolute !important; overflow: hidden; width:inherit !important"
      >
        <el-table-column width="35">
                    <template #default="scope"  v-show="true">
                      <!-- {{testLog(scope)}} -->
            <el-checkbox v-model="scope.row.checked" @change="customSelect($event,scope.row)"></el-checkbox>
                      </template>
        </el-table-column>
                <el-table-column prop="name" :label='$l("Name")' sortable :width="fileWrapperWidth  > 250 ? '' : '109'">
                          <template #default="scope">
```

**Comment by Ryan2128** [comment]
cc @justwiner

**Comment by JeremyWuuuuu** [comment]
Seems like during the initial rendering phase the table was creating virtual elements to get the template layout, we will find a way to fix it.

**Comment by justwiner** [comment]
@vadimt2 
Now the latest version should not have such a problem, can you provide a test case on `CodeOpen`?

**Comment by vadimt2** [comment]
I was using the last version.
Unfortunately i can't, i can't show all the code expect what i have provided above

**Comment by justwiner** [comment]
hey, @vadimt2 
In the latest version, `scope.row` It will not be undefined, It has always been the correct value, under normal circumstances, no error will be throw.
I may not understand your question, if other bugs are generated here, you can provide a demo for testing only, without your business code, maybe on `codeopen`

**Comment by kaiyum2012** [comment]
@JeremyWuuuuu is this issue solved? Since I am facing same issue with my code. 
I still get `scope undefine` error.
