### ISSUE TITLE
[Build] [All] vite optimizeDeps: Error: No known conditions for "./global" specifier in "element-plus" package

### ISSUE THREAD

**Issue by AndreasMietk** [element-plus/element-plus#17524]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.4.26`
- Element Plus Version: `2.3.8`
- Browser / OS: `Kubuntu 22.04 - Microsoft Edge Version 126.0.2592.81 (Official build) (64-bit)`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/devbox/focused-breeze-6vf2l3?workspaceId=94561376-a1ec-4c5a-8c72-37f9c7877bf1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyigiunt0007396protqmlwx%2522%252C%2522sizes%2522%253A%255B54.624846825599555%252C45.375153174400445%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyigiuns0002396pp39vgch6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyigiuns0004396pqdzaoa4l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyigiunt0006396ps45ou93l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.52055488233701%252C37.47944511766299%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyigiuns0002396pp39vgch6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyigiuns0001396phvn4yuml%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyigklnv0017396p7u11rds1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyigiuns0002396pp39vgch6%2522%252C%2522activeTabId%2522%253A%2522clyigklnv0017396p7u11rds1%2522%257D%252C%2522clyigiunt0006396ps45ou93l%2522%253A%257B%2522id%2522%253A%2522clyigiunt0006396ps45ou93l%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clyigl8qr000g396ptlgraddj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clyigl8qr000g396ptlgraddj%2522%257D%252C%2522clyigiuns0004396pqdzaoa4l%2522%253A%257B%2522id%2522%253A%2522clyigiuns0004396pqdzaoa4l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyigiuns0003396p0uagn96s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520install%2520vite%25405.3.3%2522%252C%2522id%2522%253A%2522clyigsjlc0080396p671b8q1l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clyigiuns0003396p0uagn96s%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

include element-plus like this in `vite.config.ts`
```typescript
    optimizeDeps: {
      include: ['element-plus/**']
    },
```

### What is Expected?

The command `vite` builds and starts the project

### What is actually happening?

This Error when using the `vite` command

```bash
error when starting dev server:
Error: No known conditions for "./global" specifier in "element-plus" package
    at e (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:21445:25)
    at n (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:21445:646)
    at o (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:21445:1297)
    at resolveExportsOrImports (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28746:20)
    at resolveDeepImport (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28765:31)
    at tryNodeResolve (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28453:20)
    at Context.resolveId (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28212:28)
    at Object.resolveId (file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44276:64)
    at async file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65937:21
    at async file:///project/sandbox/node_modules/.pnpm/vite@4.5.3/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44925:20
 ELIFECYCLE  Command failed with exit code 1.
```

### Additional comments

I get this error from `element-plus` version `2.3.8` to current `2.7.7`

**A possible fix for this is to add "es6 import" entries to the `"./global":`, `"./lib":`, `"./lib./*.js":` and `"./lib/*":` in `exports` of the `package.json`**

**Comment by warmthsea** [comment]
Deleting these codes will make it work?

```
optimizeDeps: {
   include: ['element-plus/**']
},
```

**Comment by AndreasMietk** [comment]
> Deleting these codes will make it work?
> 
> ```
> optimizeDeps: {
>    include: ['element-plus/**']
> },
> ```

yes, but this causes a different issue in our project, we need it :(

**Comment by warmthsea** [comment]
You can consider using other methods to `optimizeDeps` your package. The following is just a reference:

```
const viteDevIncludeList: string[] = await readElementPlusComponents()
```
``` ts
import path from 'node:path'
import fs from 'node:fs'

export async function readElementPlusComponents(): Promise<string[]> {
  const viteDevIncludeList: string[] = [
    'element-plus/es',
  ]
  const elementPlusDir = path.join('node_modules', 'element-plus', 'es', 'components')

  return new Promise((resolve, reject) => {
    fs.readdir(elementPlusDir, (err, files) => {
      if (err) {
        console.error('Error reading directory:', err)
        reject(err)
        return
      }

      Promise.all(
        files.map((file) => {
          return new Promise<void>((resolve, reject) => {
            const filePath = path.join(elementPlusDir, file)
            fs.stat(filePath, (err, stats) => {
              if (err) {
                console.error('Error getting file stats:', err)
                reject(err)
                return
              }

              const directoryPath = `element-plus/es/components/${file}/style/index`

              if (stats.isDirectory()) {
                const isHave = fs.existsSync(path.join('node_modules', `${directoryPath}.d.ts`))
                isHave && viteDevIncludeList.push(directoryPath)
              }

              resolve()
            })
          })
        }),
      )
        .then(() => {
          resolve(viteDevIncludeList)
        })
        .catch((err) => {
          reject(err)
        })
    })
  })
}
```

**vite.config.ts**
```
optimizeDeps: {
      include: [...viteDevIncludeList],
},
```

**Comment by AndreasMietk** [comment]
Thank you very much, i will try this out later :+1:
