### ISSUE TITLE
[Component] [message-box] ElMessageBox 与 vueI18n 组合bug

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#18503]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1. 按需导入方式，使用 H 函数创建组件，如下代码

```ts
ElMessageBox({
        title: t('title.prepareUploadFiles'),
        draggable: true,
        closeOnClickModal: false,
        customStyle: { maxWidth: confirmFileList.length > 1 ? '505px' : '270px', width: 'auto' },
        message: () =>
          h(
            'div',
            {
              style: {
                height: confirmFileList.length > 8 ? '310px' : '',
              },
            },
            h(ElScrollbar, {}, () =>
              h(
                TransitionGroup,
                { tag: 'div', name: 'sp-list-translate-x', class: ['flex', 'flex-wrap', 'gap-1'] },
                () =>
                  confirmFileList.map((file, index) => {
                    return h(SpFile, {
                      key: file.key,
                      fileName: file.file.name,
                      fileSize: file.file.size,
                      thumbnailUrl: file.thumbnailUrl,
                      deleteEnabled: true,
                      onDelete: () => {
                        confirmFileList.splice(index, 1);
                        if (confirmFileList.length === 0) {
                          ElMessageBox.close();
                        }
                      },
                    });
                  }),
              ),
            ),
          ),
        showCancelButton: true,
      })
        .then(() => {
          upload();
        })
        .catch(() => {
          confirmFileList.splice(0);
        });
    }
```

2. `SpFile` 是一个组件，里面只要是用 vueI18n 就会报错
```
SpFile.vue:88 [Vue warn]: Property "$t" was accessed during render but is not defined on instance. 
  at <SpFile key="mwOBDqxdVUXgd9dygRpXs" fileName="54604325_p0.jpg" fileSize=205275  ... > 
  at <TransitionGroup tag="div" name="sp-list-translate-x" class="flex flex-wrap gap-1" > 
  at <ElScrollbar > 
  at <ElFocusTrap loop="" trapped=true focus-trap-el= 
  ... > 
  at <ElOverlay z-index=2030 overlay-class= 
(2) ['is-message-box', '']
 mask=true > 
  at <BaseTransition onAfterLeave=fn<onAfterLeave> appear=false persisted=true  ... > 
  at <Transition name="fade-in-linear" onAfterLeave=fn<onAfterLeave> persisted="" > 
  at <ElMessageBox title="准备上传的文件" draggable=true closeOnClickModal=false  ... >
index.ts:88 [Vue warn]: Unhandled error during execution of render function 
  at <SpFile key="mwOBDqxdVUXgd9dygRpXs" fileName="54604325_p0.jpg" fileSize=205275  ... > 
  at <TransitionGroup tag="div" name="sp-list-translate-x" class="flex flex-wrap gap-1" > 
  at <ElScrollbar > 
  at <ElFocusTrap loop="" trapped=true focus-trap-el= 
  ... > 
  at <ElOverlay z-index=2030 overlay-class= 
(2) ['is-message-box', '']
 mask=true > 
  at <BaseTransition onAfterLeave=fn<onAfterLeave> appear=false persisted=true  ... > 
  at <Transition name="fade-in-linear" onAfterLeave=fn<onAfterLeave> persisted="" > 
  at <ElMessageBox title="准备上传的文件" draggable=true closeOnClickModal=false  ... >
index.ts:88 [Vue warn]: Unhandled error during execution of component update 
  at <BaseTransition onAfterLeave=fn<onAfterLeave> appear=false persisted=true  ... > 
  at <Transition name="fade-in-linear" onAfterLeave=fn<onAfterLeave> persisted="" > 
  at <ElMessageBox title="准备上传的文件" draggable=true closeOnClickModal=false  ... >
index.ts:88 [Vue warn]: Unhandled error during execution of mounted hook 
  at <ElMessageBox title="准备上传的文件" draggable=true closeOnClickModal=false  ... >
SpFile.vue:88 Uncaught (in promise) TypeError: _ctx.$t is not a function
    at Proxy._sfc_render (SpFile.vue:88:19)
    at renderComponentRoot (chunk-U53QWLOP.js?v=cfb7a1c3:7744:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-U53QWLOP.js?v=cfb7a1c3:6587:46)
    at ReactiveEffect.run (chunk-U53QWLOP.js?v=cfb7a1c3:1830:23)
    at setupRenderEffect (chunk-U53QWLOP.js?v=cfb7a1c3:6722:5)
    at mountComponent (chunk-U53QWLOP.js?v=cfb7a1c3:6497:7)
    at processComponent (chunk-U53QWLOP.js?v=cfb7a1c3:6450:9)
    at patch (chunk-U53QWLOP.js?v=cfb7a1c3:5966:11)
    at mountChildren (chunk-U53QWLOP.js?v=cfb7a1c3:6198:7)
    at mountElement (chunk-U53QWLOP.js?v=cfb7a1c3:6121:7)
SpFile.vue:88 Uncaught (in promise) TypeError: _ctx.$t is not a function
    at Proxy._sfc_render (SpFile.vue:88:19)
    at renderComponentRoot (chunk-U53QWLOP.js?v=cfb7a1c3:7744:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-U53QWLOP.js?v=cfb7a1c3:6587:46)
    at ReactiveEffect.run (chunk-U53QWLOP.js?v=cfb7a1c3:1830:23)
    at setupRenderEffect (chunk-U53QWLOP.js?v=cfb7a1c3:6722:5)
    at mountComponent (chunk-U53QWLOP.js?v=cfb7a1c3:6497:7)
    at processComponent (chunk-U53QWLOP.js?v=cfb7a1c3:6450:9)
    at patch (chunk-U53QWLOP.js?v=cfb7a1c3:5966:11)
    at mountChildren (chunk-U53QWLOP.js?v=cfb7a1c3:6198:7)
    at mountElement (chunk-U53QWLOP.js?v=cfb7a1c3:6121:7)
SpFile.vue:88 Uncaught (in promise) TypeError: _ctx.$t is not a function
    at Proxy._sfc_render (SpFile.vue:88:19)
    at renderComponentRoot (chunk-U53QWLOP.js?v=cfb7a1c3:7744:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-U53QWLOP.js?v=cfb7a1c3:6587:46)
    at ReactiveEffect.run (chunk-U53QWLOP.js?v=cfb7a1c3:1830:23)
    at setupRenderEffect (chunk-U53QWLOP.js?v=cfb7a1c3:6722:5)
    at mountComponent (chunk-U53QWLOP.js?v=cfb7a1c3:6497:7)
    at processComponent (chunk-U53QWLOP.js?v=cfb7a1c3:6450:9)
    at patch (chunk-U53QWLOP.js?v=cfb7a1c3:5966:11)
    at mountChildren (chunk-U53QWLOP.js?v=cfb7a1c3:6198:7)
    at mountElement (chunk-U53QWLOP.js?v=cfb7a1c3:6121:7)
```

### 这种情况会报错

1. 当在标签中使用 `$t`
2. 在 setup 中使用 useI18n()

### 这种情况下不会报错

1. 直接从 `i18n.global.t` 获取 `t` 函数

### 这样操作后就不会报错
1. 全局注册 `ElMessageBox` 即可
2. 或者全局注册 ElementPlus

### What is Expected?

希望没有报错，这个问题不知道是 ElMessageBox 的问题还是 `i18n` 的问题，目前不知道原理。

### What is actually happening?

如果能解决最好，感觉这个错误很有意思。无法解决如果有大神能解释原因也可以，因为我可以全局注册 ElMessageBox 来解决这个问题。

### Additional comments

_(empty)_

**Comment by btea** [comment]
请提供一份复现代码。

**Comment by WangJincheng4869** [comment]
> 请提供一份复现代码。

[packages/el-i18n](https://github.com/WangJincheng4869/fanKuiWenJian/tree/main/packages/el-i18n)

**Comment by btea** [comment]
如果你配置了`app.use(ElMessageBox)`，那么就会触发`install`函数，`app._context`就会赋值给`MessageBox._context`。
https://github.com/element-plus/element-plus/blob/72dd11aac271e788da45e0e92b3ad3dd343c1601/packages/components/message-box/index.ts#L8-L15
https://github.com/element-plus/element-plus/blob/72dd11aac271e788da45e0e92b3ad3dd343c1601/packages/components/message-box/src/messageBox.ts#L239

当进行函数调用时会把相关配置传给`MessageBox`上下文。
https://github.com/element-plus/element-plus/blob/72dd11aac271e788da45e0e92b3ad3dd343c1601/packages/components/message-box/src/messageBox.ts#L164-L167

子组件渲染时，会从父组件继承`globalProperties`相关配置。因此，如果父组件没有配置相关属性，子组件也就不存在相关属性。

以下是点击`弹出`按钮时，`getCurrentInstance()`返回的对象中`globalProperties`的配置对比情况。
<table>
<tr>
<td>在`main.ts`中调用`app.use(ElMessageBox)`</td>
<td>没有调用`app.use(ElMessageBox)`</td>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/c0074538-8a3f-4996-bb9a-23343bd0e980)
</td>
<td>

![image](https://github.com/user-attachments/assets/cf24a0c9-116e-4faa-b564-94348c0b076a)

</td>
</tr>
</table>

**Comment by WangJincheng4869** [comment]
@btea 那么这个算是 bug 还是机制？看上去貌似不仅仅是 i18n 会有这样的问题，是不是用 useRouter 或者 alert 也会有类似的问题？

**Comment by btea** [comment]
不是bug，ElMessageBox和根组件没有继承关系。你要么在组件`helloworld.vue`中手动引入`vue-i18n`，要么就像现在使用`app.use(ElMessageBox)`来继承全局属性配置。

**Comment by WangJincheng4869** [comment]
> 不是bug，ElMessageBox和根组件没有继承关系。你要么在组件`helloworld.vue`中手动引入`vue-i18n`，要么就像现在使用`app.use(ElMessageBox)`来继承全局属性配置。

OK 明白，可以在按需导入的文档中添加提示条（因为在按需导入时不会 use ElementPlus），提醒注册此组件，防止其他人再次遇见此类问题。

**Comment by btea** [comment]
可以加一下。
