### ISSUE TITLE
[Component] [message, icon] 按需引入组件时message和icon有问题

### ISSUE THREAD

**Issue by KeepInlove** [element-plus/element-plus#19146]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.29`
- Element Plus Version: `2.3.1`
- Browser / OS: `131.0.6778.87`
- Build Tool: `Vite`

### Related Component

- `el-message`
- `el-icon`

### Reproduction Link

[Github Repo](https://github.com/sxzz/element-plus-best-practices/blob/db2dfc983ccda5570033a0ac608a1bd9d9a7f658/vite.config.ts#L21-L58)

### Steps to reproduce

下面是按需引入配置文件vite.config.js： import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import Icons from 'unplugin-icons/vite'
import IconsResolver from 'unplugin-icons/resolver'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
import { resolve } from 'path'

export default defineConfig({
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  plugins: [
    vue(),
    AutoImport({
      // 自动导入 Vue 相关函数，如：ref, reactive, toRef 等
      imports: ['vue'],
      // 自动导入 Element Plus 相关函数，如：ElMessage, ElMessageBox 等
      resolvers: [
        ElementPlusResolver(),
        // 自动导入图标组件
        IconsResolver({
          prefix: 'Icon',
        }),
      ],
      dts: 'src/auto-imports.d.ts',
      eslintrc: {
        enabled: true, // 自动生成 ESLint 配置
        filepath: './.eslintrc-auto-import.json', // 生成的 ESLint 配置文件路径
        globalsPropValue: true, // ESLint 全局变量设置
      },
    }),
    Components({
      resolvers: [
        // 自动注册图标组件
        IconsResolver({
          enabledCollections: ['ep'],
        }),
        // 自动注册 Element Plus 组件
        ElementPlusResolver(),
      ],
      dts: 'src/components.d.ts',
    }),
    Icons({
      autoInstall: true,
    }),
  ],
}) 示例代码：import { ElMessage } from 'element-plus'
 <el-button size="large"  type="primary" @click="open4">
          注册
        </el-button> <template #prefix>
            <el-icon><Lock /></el-icon>
          </template> const open4 = () => {
  ElMessage.success("短信发送成功");
} 组件ElMessage报错： TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them 
    at Function.invokeGetter (<anonymous>:3:28)
    at open4 (http://localhost:5173/src/view/common/components/register-form.vue:62:3)
    at callWithErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:1678:19)
    at callWithAsyncErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:1685:17)
    at emit (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:2210:5)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:9282:45
    at handleClick (http://localhost:5173/node_modules/.vite/deps/chunk-RTQLLXMC.js?v=50f50bf3:24367:5)
    at callWithErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:1678:19)
    at callWithAsyncErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:1685:17)
    at HTMLButtonElement.invoker (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=50f50bf3:10320:5)

### What is Expected?

不应该报错

### What is actually happening?

报错message不弹框显示

### Additional comments

但是使用全局引用main.js文件：import { createApp } from 'vue'
import './style.css'
import App from './App.vue'

// 引入ElementPlus图标组件
import * as ElementPlusIconsVue from '@element-plus/icons-vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import router from "./router";
import axios from 'axios';
import registerInterceptors from '@/api/interceptor';
let app = createApp(App);
app.use(ElementPlus)
app.use(router)
for (const [key, component] of Object.entries(ElementPlusIconsVue)) {
    app.component(key, component)
}
// 注册 Axios 全局方法
app.config.globalProperties.$axios = axios;
// 注册请求和响应拦截器
registerInterceptors(axios);
app.mount('#app')
我debug发现：异常：TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28) at open4 (http://localhost:5173/src/view/common/components/register-form.vue:55:3) at callWithErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=4bb80953:1678:19) at callWithAsyncErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=4bb80953:1685:17) at emit (http://localhost:5173/node_modules/.vite/deps/chunk-ZJ5FW67J.js?v=4bb80953:2210: 依然报错，但是可以正常弹框

**Comment by tolking** [comment]
可以参考[最新的模版](https://github.com/element-plus/element-plus-vite-starter)使用
