### ISSUE TITLE
[bug report] SSR cascade select unknown error prompt

### ISSUE THREAD

**Issue by yang867381349** [element-plus/element-plus#2486]
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
Google Chrome 已是最新版本 版本 91.0.4472.114（正式版本） (x86_64)

### Vue version
3.1.4

### Reproduction Link
https://github.com/yang867381349/error

### Steps to reproduce
ssr   element-plus  通过 express 服务代理预渲染 数据预加载 想显示执行出     Cascader 级联选择器     Select 选择器  启动提示错误

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at vue.watch.deep (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/element-plus/lib/el-cascader-panel/index.js:808:59)
    at callWithErrorHandling (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at callWithAsyncErrorHandling (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
    at doWatch (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2017:13)
    at Object.watch (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1930:12)
    at setup (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/element-plus/lib/el-cascader-panel/index.js:808:9)
    at callWithErrorHandling (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7097:29)
    at setupComponent (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7053:11)
    at renderComponentVNode (/Users/tg/瀹夊窘鐭ュ€肩綉淇℃伅鎶€鏈湁闄愬叕鍙�/nuxt-protal/fdsafd/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:17)

### What is Expected?
有什么方式方法解决当前的问题

### What is actually happening?
已超出我的能力范围。希望官方人员给出提示，感谢！

**Comment by yang867381349** [comment]
希望大佬们给我一点提示

**Comment by yang867381349** [comment]
@bmfs

**Comment by yang867381349** [comment]
大佬们 可以看看到底是什么原因导致的

**Comment by ioslh** [comment]
That might be a vue's bug, we are still carefully inspect on this.
For a temp solution, you can change your code to something like this:

```vue
<el-cascader v-if="show" />


<script>
const show = ref(false)
onMounted(() => {
  show.value = true
})
<script>
```

**Comment by yang867381349** [comment]
> 这可能是 vue 的 bug，我们仍在仔细检查。
> 作为临时解决方案，您可以将代码更改为如下所示：
> 
> ```
> < el-cascader  v-if = " show " />
> 
> 
> <脚本>
> 常量 放映 =  REF（假）
> onMounted（（）=> {
> 显示。值=真}）</脚本>    
> ```

Thank you. Thank you. Thank you. I asked a lot about this problem, but no one solved it. I've been doing it myself for two days. I'm almost disheartened. This is my wechat YJQ867381349

**Comment by yang867381349** [comment]
> That might be a vue's bug, we are still carefully inspecting on this.
> As a temp solution, you can change your code to something like this:
> 
> ```
> <el-cascader v-if="show" />
> 
> 
> <script>
> const show = ref(false)
> onMounted(() => {
>   show.value = true
> })
> </script>
> ```

Thank you. Thank you. Thank you. I asked a lot about this problem, but no one solved it. I've been doing it myself for two days. I'm almost disheartened. This is my wechat YJQ867381349
