### ISSUE TITLE
SSR support | 服务端渲染相关问题

### ISSUE THREAD

**Issue by JeremyWuuuuu** [element-plus/element-plus#2612]
Hey guys, please report any SSR related issue here and we will going to fix them ASAP, this should be our first priority.

Thank you all for being patient and supportive for ElementPlus. 🙏

大家好，如果你们在项目中发现 ElementPlus 和 SSR 不太对劲的地方，请在这个 issue 里留言，我们会优先修复 SSR 相关的问题。
非常感谢大家一直以来对 ElementPlus 的支持与耐心，你们的留言会帮助 ElementPlus 成长为一个更好的项目。谢谢！🙏

**Comment by L-H-U** [comment]
ReferenceError: Image is not defined
at Object.script.install (/Users/Working/node_modules/element-plus/lib/el-image-viewer/index.js:380:17)
at Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
at /Users/Working/node_modules/element-plus/lib/index.js:327:13
at Array.forEach ()
at Object.install (/Users/Working/node_modules/element-plus/lib/index.js:326:29)
at Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
at Module.createApp (/src/main.js:22:6)
at render (/src/entry-server.js:6:46)
at /Users/Working/server.js:64:62

vite+ssr+vue3 环境下有报这个错误

**Comment by yang867381349** [comment]
我今天也遇到这个问题。不知道怎么解决。搞的一头雾水。说 element-plus 里面有 创建 对象图片？？？？？？？？？

**Comment by yang867381349** [comment]
@JeremyWuuuuu 这个问题能否尽快解决。我们做ssr 遇到这个问题了

**Comment by yang867381349** [comment]
> ReferenceError: Image is not defined
> at Object.script.install (/Users/Working/node_modules/element-plus/lib/el-image-viewer/index.js:380:17)
> at Object.use (/Users/Working/ node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
> 在 /Users/Working/node_modules/element-plus/lib/index.js:327:13
> 在 Array.forEach ()
> 在 Object.install (/Users/Working/node_modules/element-plus/lib/index.js:326:29)
> 在 Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime -core.cjs.prod.js:3050:28)
> at Module.createApp (/src/main.js:22:6)
> at render (/src/entry-server.js:6:46)
> at /Users/Working /server.js:64:62
> 
> vite+ssr+vue3+element-plus@latest 环境下有报这个错误
> 
> 1.0.2-beta.55版本没有这个问题

大佬们你们是如何解决的？我怎么解决这个问题。我好头疼啊

**Comment by Hlianfa** [comment]
@JeremyWuuuuu

popper 功能异常，我这里使用的是 el-select，点击后唤起了当前页面上多个 popper，同时控制台报以下错误

`arrow.js:83 Popper: "arrow" modifier's `element` must be a child of the popper element.
effect2 @ arrow.js:83
(anonymous) @ createPopper.js:233
runModifierEffects @ createPopper.js:226
setOptions @ createPopper.js:114
createPopper4 @ createPopper.js:215
initializePopper @ index.js:307
onVisibilityChange @ index.js:334
callWithErrorHandling @ runtime-core.esm-bundler.js:6666
...`

版本信息
`"element-plus": "^1.1.0-beta.15",
 "vue": "^3.2.14",
 "vite": "^2.5.10"
`
