### ISSUE TITLE
Form warning

### ISSUE THREAD

**Issue by stgzhangzheyi** [element-plus/element-plus#2615]
更新版本之后，为什么会出现这种警告。webpack-internal:///./node_modules/element-plus/lib/index.esm.js:138 ElementPlusError: [Util] binding value must be a string or number
    at $e (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:138:719)
    at nt (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:138:1996)
    at eval (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:138:306784)
    at ComputedRefImpl.reactiveEffect [as effect] (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:71:24)
    at ComputedRefImpl.get value [as value] (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:890:32)
    at unref (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:804:29)
    at Object.get (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:807:37)
    at Object.get (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6302:34)
    at Proxy.os.render (webpack-internal:///./node_modules/element-plus/lib/index.esm.js:138:311027)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:965:44)

**Comment by tolking** [comment]
link: #2525

**Comment by stgzhangzheyi** [comment]
> link: #2525



> 链接：#2525

1.0.2-beta.56版本才修复这个问题？？？？？请问大概什么时候呢？

**Comment by kooriookami** [comment]
@tolking @stgzhangzheyi We will release 1.0.2-beta.56 tomorrow. Sorry for inconvenience.

**Comment by stgzhangzheyi** [comment]
> @tolking @stgzhangzheyi我们将在明天发布 1.0.2-beta.56。对造成的不便表示歉意。
好的，谢谢您

**Comment by hhyygg2009** [comment]
I have the same problem.Hope we can get next version early.

**Comment by JeremyWuuuuu** [comment]
Guys, I need to ask you a question:

We are making changes to our `theme` implementation and it has been for like 2 weeks now, we are currently in the middle of migration (pardon our poor project management) so the thing is in order to fix this we need to release a new version which would potentially break someone's `customize theme` functionality do you think that is acceptable? @hhyygg2009 @stgzhangzheyi @tolking

**Comment by JeremyWuuuuu** [comment]
I'm only ask because we care about our users, the experiences but for now we are in the middle of transition, so that transition could've been painful (for a while) but for better good we need to get pass that pain. Let me know WDYT. :bow:

**Comment by tolking** [comment]
@JeremyWuuuuu It will be acceptable after finishing the `customize theme`

**Comment by kooriookami** [comment]
Fixed in 1.0.2-beta.56.
