### ISSUE TITLE
ReferenceError: Image is not defined

### ISSUE THREAD

**Issue by L-H-U** [element-plus/element-plus#2682]
ReferenceError: Image is not defined
 at Object.script.install (/Users/Working/node_modules/element-plus/lib/el-image-viewer/index.js:380:17)
    at Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
    at /Users/Working/node_modules/element-plus/lib/index.js:327:13
    at Array.forEach (<anonymous>)
    at Object.install (/Users/Working/node_modules/element-plus/lib/index.js:326:29)
    at Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
    at Module.createApp (/src/main.js:22:6)
    at render (/src/entry-server.js:6:46)
    at /Users/Working/server.js:64:62

vite+ssr+vue3 环境下有报这个错误

**Comment by L-H-U** [comment]
> ReferenceError: Image is not defined
> at Object.script.install (/Users/Working/node_modules/element-plus/lib/el-image-viewer/index.js:380:17)
> at Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
> at /Users/Working/node_modules/element-plus/lib/index.js:327:13
> at Array.forEach ()
> at Object.install (/Users/Working/node_modules/element-plus/lib/index.js:326:29)
> at Object.use (/Users/Working/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3050:28)
> at Module.createApp (/src/main.js:22:6)
> at render (/src/entry-server.js:6:46)
> at /Users/Working/server.js:64:62
> 
> vite+ssr+vue3 环境下有报这个错误
