### ISSUE TITLE
[Bug Report] el-menu: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

### ISSUE THREAD

**Issue by jiaozhiye** [element-plus/element-plus#3159]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
chrome 92

### Vue version
3.2.6

### Steps to reproduce
上一个版本是没有问题的，更新到 1.1.0-beta.8 出现的警告！
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
  at <ElMenu router=true collapse=false collapseTransition=false  ... >

### What is Expected?
希望不要出现警告！

**Comment by xiaotongXT** [comment]
我也碰到这个警告了，而且不能正常渲染。采用的是vue3.2 jsx的写法，之前的版本没有此错误。
demo写法如下
<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    const activeIndex = ref("1");
    const handleSelect = (key, keyPath) => {
      console.log(key, keyPath);
    };
    return () => (
      <el-menu
        default-active={activeIndex.value}
        class="el-menu-demo"
        mode="horizontal"
        onSelect={handleSelect}
      >
      <el-menu-item index="1">处理中心</el-menu-item>
      </el-menu>
    )
  },
});
</script>

**Comment by xiaotongXT** [comment]
我也碰到这个警告了，而且不能正常渲染。采用的是vue3.2 jsx的写法，之前的版本没有此错误。

**Comment by cykcykcykcyk** [comment]
我也遇到了，虽然可以正常使用，但是爆黄有点不爽

**Comment by bowencool** [comment]
一样遇到了。
借楼再贴一个警告：
```
[Vue warn]: Maximum recursive updates exceeded in component <ElSubMenu>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8088:13)
      at checkRecursiveUpdates (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8570:7)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8537:21)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8556:7)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8556:7)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8556:7)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8556:7)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:8556:7)
```

**Comment by EmandM** [comment]
I am also seeing this issue

**Comment by xw5** [comment]
I am also seeing this issue 2.12.0版本

**Comment by xw5** [comment]
在2.12.0版本中使用el-select的时候遇到这个警告

**Comment by babalrlr** [comment]
> 在2.12.0版本中使用el-select的时候遇到这个警告

[目测是这里发出的警告](https://github.com/element-plus/element-plus/blob/fc2a003ff8d3936d67a94fe29168c41ff877ca40/packages/components/select/src/select.vue#L505)
