### ISSUE TITLE
[Bug Report] el-container , Cannot read property 'isCE' of null

### ISSUE THREAD

**Issue by oooowl** [element-plus/element-plus#4528]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
win10

### Vue version
3.2.22

### Reproduction Link
https://stackblitz.com/edit/github-9ukebr?file=layouts%2Fdefault.vue

### Steps to reproduce
in nuxt3 build && start

### What is actually happening?
useAsyncData not work in first render

`
TypeError: Cannot read property 'isCE' of null
    at Object.renderSlot (C:\Users\10460432\Desktop\nuxt3-app\.output\server\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5770:34)
    at Proxy.render (C:\Users\10460432\Desktop\nuxt3-app\.output\server\node_modules\element-plus\lib\components\container\src\container.vue_vue&type=template&id=60a2865a&lang.js:11:9)
    at renderComponentRoot (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:2015:44)
    at renderComponentSubTree (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:9829:51)
    at renderComponentVNode (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:9774:16)
    at Object.ssrRenderComponent (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:10183:12)
    at _sfc_ssrRender$2 (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/server.mjs:6190:32)
    at renderComponentSubTree (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:9823:13)
    at renderComponentVNode (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:9774:16)
    at renderVNode (file:///C:/Users/10460432/Desktop/nuxt3-app/.output/server/chunks/index.mjs:9864:22)
`

**Comment by sxzz** [comment]
Please provide a reproduction link and reopen this issue.

**Comment by oooowl** [comment]
Reproduction Link was added

**Comment by sxzz** [comment]
I tried your reproduction link, and no error was emited.

**Comment by oooowl** [comment]
> I tried your reproduction link, and no error was emited.

Do npm run build , and npm run start

**Comment by lemoe2021** [comment]
same error when I try to install this package locally

**Comment by xiaoxian521** [comment]
Solved: [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter)
<img width="941" alt="image" src="https://user-images.githubusercontent.com/44761321/155045960-3dddc2a8-2947-4678-81c3-983a8299d4b9.png">
