### ISSUE TITLE
[Bug Report] run `pnpm build` fail

### ISSUE THREAD

**Issue by Kimwill** [element-plus/element-plus#4537]
### Element Plus version
1.2.0-beta.3

### OS/Browsers version
window 10 

### Vue version
3.2.22

### Reproduction Link
https://github.com/element-plus/element-plus/

### Steps to reproduce
pnpm i
pnpm build

### What is Expected?
build success

### What is actually happening?
> @ build E:\test\vue\element-plus-dev\element-plus-dev  
> gulp --require sucrase/register/ts -f build/gulpfile.ts

[23:41:57] Requiring external module sucrase/register/ts
[23:41:57] Working directory changed to E:\test\vue\element-plus-dev\element-plus-dev\build
Error: Cannot find module '../packages/element-plus/version'
Require stack:
- E:\test\vue\element-plus-dev\element-plus-dev\build\full-bundle.ts
- E:\test\vue\element-plus-dev\element-plus-dev\build\gulpfile.ts
- E:\test\vue\element-plus-dev\element-plus-dev\node_modules\.pnpm\gulp-cli@2.3.0\node_modules\gulp-cli\lib\shared\require-or-import.js
- E:\test\vue\element-plus-dev\element-plus-dev\node_modules\.pnpm\gulp-cli@2.3.0\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- E:\test\vue\element-plus-dev\element-plus-dev\node_modules\.pnpm\gulp-cli@2.3.0\node_modules\gulp-cli\index.js
- E:\test\vue\element-plus-dev\element-plus-dev\node_modules\.pnpm\gulp@4.0.2\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\test\vue\element-plus-dev\element-plus-dev\build\full-bundle.ts:10:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (E:\test\vue\element-plus-dev\element-plus-dev\node_modules\.pnpm\pirates@4.0.1\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .ts] (E:\test\vue\element-plus-dev\element-plus-dev\node_modules\.pnpm\pirates@4.0.1\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\test\\vue\\element-plus-dev\\element-plus-dev\\build\\full-bundle.ts',
    'E:\\test\\vue\\element-plus-dev\\element-plus-dev\\build\\gulpfile.ts',
    'E:\\test\\vue\\element-plus-dev\\element-plus-dev\\node_modules\\.pnpm\\gulp-cli@2.3.0\\node_modules\\gulp-cli\\lib\\shared\\require-or-import.js',
    'E:\\test\\vue\\element-plus-dev\\element-plus-dev\\node_modules\\.pnpm\\gulp-cli@2.3.0\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'E:\\test\\vue\\element-plus-dev\\element-plus-dev\\node_modules\\.pnpm\\gulp-cli@2.3.0\\node_modules\\gulp-cli\\index.js',
    'E:\\test\\vue\\element-plus-dev\\element-plus-dev\\node_modules\\.pnpm\\gulp@4.0.2\\node_modules\\gulp\\bin\\gulp.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.

**Comment by sxzz** [comment]
Please run `pnpm run gen:version`

**Comment by Kimwill** [comment]
I continue to run `pnpm build`, get the error:

![image](https://user-images.githubusercontent.com/37266209/143726973-bc60d8a6-352e-42ca-9958-4a6a0ba7b483.png)
![image](https://user-images.githubusercontent.com/37266209/143726982-1777375d-a7b1-473a-9304-9ca244df09e3.png)

And the dist I got should be incomplete

Which step am I missing?

**Comment by sxzz** [comment]
Are you using windows? Currently building on windows is not supported.
