### ISSUE TITLE
Cannot find module 'fork-ts-checker-webpack-plugin-v5'

### ISSUE THREAD

**Issue by xlanghejianfeng** [element-plus/element-plus#464]

**Comment by xlanghejianfeng** [comment]
node:v11.15.0
npm:6.7.0
 "element-plus": "^1.0.1-alpha.10"

**Comment by zazzaz** [comment]
Hi, any more error info you could provide. Where's this `fork-ts-checker-webpack-plugin-v5` comes from?

**Comment by xlanghejianfeng** [comment]
npm install element-plus --save -D

npm run server    error info not work

**Comment by JeremyWuuuuu** [comment]
Unless you give us a detailed error report, we could not provide any help with poor info.

**Comment by xlanghejianfeng** [comment]
first error is  Cannot find module 'vue-loader-v16/package.json'

**Comment by JeremyWuuuuu** [comment]
Could you please paste all error reported from your terminal here?

**Comment by JeremyWuuuuu** [comment]
I think we are having a bad conversation here, providing useless information could not help you nor us to find the way to help you solving this problem. Please provide a detailed error report to us

BTW,  we suggest you to try Node v14+ to run this project. If you already have node natively installed you might need to try `nvm` for a alternative version

**Comment by xlanghejianfeng** [comment]
node V15

**Comment by xlanghejianfeng** [comment]
可以添加微信私聊么，现在这个框架还比较新 想引入项目做调研

**Comment by zazzaz** [comment]
Hi, you can check this project as a reference https://github.com/element-plus/element-plus-starter

**Comment by xlanghejianfeng** [comment]
Dara:vue3.0-element-plus-demo imike$ npm run serve

> vue3.0-element-plus-demo@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
Require stack:
- /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-plugin-typescript/index.js
- /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/Service.js
- /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
Require stack:
- /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-plugin-typescript/index.js
- /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/Service.js
- /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-plugin-typescript/index.js:89:16
    at /Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at Service.resolveWebpackConfig (/Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (/Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/commands/serve.js:75:31)
    at Service.run (/Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/Users/blake/LuoJin/project/vue3.0-element-plus-demo/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
npm ERR! code 1
npm ERR! path /Users/blake/LuoJin/project/vue3.0-element-plus-demo
npm ERR! command failed
npm ERR! command sh -c vue-cli-service serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qiaoyi/.npm/_logs/2020-10-26T07_45_05_109Z-debug.log

**Comment by JeremyWuuuuu** [comment]
Please refer to the error message which tells you that the package/module was missing, first of all, you need to find out if the package is installed, then file this issue.

**Comment by xlanghejianfeng** [comment]
npm not fork-ts-checker-webpack-plugin-v5, only has fork-ts-checker-webpack-plugin

**Comment by JeremyWuuuuu** [comment]
Then you need to install `fork-ts-checker-webpack-plugin-v5`.
This is not a issue with ElementPlus, so I am closing this issue

**Comment by xlanghejianfeng** [comment]
maybe VUE3.0 error?

**Comment by zazzaz** [comment]
Hi, you can check this Vue3.0 + Element Plus project as a reference https://github.com/element-plus/element-plus-starter
