### ISSUE TITLE
[Bug Report] npm run build-tsc build error

### ISSUE THREAD

**Issue by peterwang1990** [element-plus/element-plus#4795]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
MacOS 12.0.1

### Vue version
3.2.24

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973

### Steps to reproduce
vite build
then raise error

my package.json

"dependencies": {
    "@efox/emp-vuett": "^1.0.0",
    "@makerdao/multicall": "^0.12.0",
    "@metamask/detect-provider": "1.2.0",
    "@sketchfab/viewer-api": "^1.10.3",
    "@vueuse/core": "^6.7.4",
    "@walletconnect/web3-provider": "1.6.6",
    "amfe-flexible": "^2.2.1",
    "autoprefixer": "^10.4.0",
    "axios": "^0.21.1",
    "bignumber.js": "9.0.1",
    "dot-prop-immutable": "2.1.1",
    "element-plus": "1.2.0-beta.6",
    "ethereumjs-util": "^7.1.3",
    "ethers": "^5.5.1",
    "fullpage.js": "^3.1.2",
    "mitt": "3.0.0",
    "moment": "2.29.1",
    "patch-package": "^6.4.7",
    "postcss-pxtorem": "^6.0.0",
    "remixicon": "^2.5.0",
    "vue": "^3.2.24",
    "vue-router": "^4.0.11",
    "vue-slidepage": "^1.0.0",
    "vuex": "^4.0.2",
    "web3": "1.6.0",
    "web3-eth": "1.6.0",
    "web3-eth-contract": "1.6.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.1",
    "@types/jest": "^26.0.22",
    "@types/lodash": "^4.14.176",
    "@types/node": "^16.11.6",
    "@types/uuid": "^8.3.1",
    "@typescript-eslint/eslint-plugin": "^4.21.0",
    "@typescript-eslint/parser": "^4.21.0",
    "@vitejs/plugin-vue": "^1.9.4",
    "@vue/compiler-sfc": "^3.2.20",
    "@vue/test-utils": "^2.0.0-rc.4",
    "commitizen": "^4.2.3",
    "cz-conventional-changelog": "^3.3.0",
    "cz-customizable": "^6.3.0",
    "eslint": "^7.24.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-import-resolver-node": "^0.3.6",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.3.5",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.8.0",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "stylus": "^0.54.8",
    "ts-jest": "^26.5.4",
    "ts-morph": "^12.2.0",
    "typescript": "^4.4.4",
    "unplugin-vue-components": "^0.17.0",
    "vite": "^2.6.13",
    "vue-jest": "^5.0.0-alpha.7",
    "vue-tsc": "^0.3.0"
  }

### What is Expected?
Could not resolve './hooks/use-{}-config/index.mjs' from node_modules/element-plus/es/index.mjs
error during build:
Error: Could not resolve './hooks/use-{}-config/index.mjs' from node_modules/element-plus/es/index.mjs
    at error (/Users/daviddai/Develop/Facts/tapfantasy/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/Users/daviddai/Develop/Facts/tapfantasy/node_modules/rollup/dist/shared/rollup.js:22263:24)
    at /Users/daviddai/Develop/Facts/tapfantasy/node_modules/rollup/dist/shared/rollup.js:22257:26

### What is actually happening?
in vite  ok
but vite build raise error

**Comment by peterwang1990** [comment]
> Hello @peterwang1990. Please provide an online reproduction demo by clicking this [link](https://codepen.io/iamkun/pen/YzWMaVr) or a minimal GitHub repository. Issues marked with `need reproduction` will be closed if they have no activity within 3 days.
> 
> 你好 @peterwang1990, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。可以通过点击 [此处](https://codepen.io/iamkun/pen/YzWMaVr) 创建或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。

你好 我已经创建了最小仓库

**Comment by xiaoxian521** [comment]
将vue版本升级到最新

**Comment by peterwang1990** [comment]
> 将vue版本升级到最新

你好我升级到最新版本 vue 3.2.26 build 依然报错


Could not resolve './hooks/use-{}-config/index.mjs' from node_modules/element-plus/es/index.mjs
error during build:
Error: Could not resolve './hooks/use-{}-config/index.mjs' from node_modules/element-plus/es/index.mjs
    at error (/Users/daviddai/Develop/Facts/tapfantasy/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/Users/daviddai/Develop/Facts/tapfantasy/node_modules/rollup/dist/shared/rollup.js:22263:24)
    at /Users/daviddai/Develop/Facts/tapfantasy/node_modules/rollup/dist/shared/rollup.js:22257:26


我的依赖


"dependencies": {
    "@makerdao/multicall": "^0.12.0",
    "@metamask/detect-provider": "1.2.0",
    "@vueuse/core": "^6.7.4",
    "@walletconnect/web3-provider": "1.6.6",
    "amfe-flexible": "^2.2.1",
    "autoprefixer": "^10.4.0",
    "axios": "^0.21.1",
    "bignumber.js": "9.0.1",
    "dot-prop-immutable": "2.1.1",
    "element-plus": "1.2.0-beta.6",
    "ethereumjs-util": "^7.1.3",
    "ethers": "^5.5.1",
    "mitt": "3.0.0",
    "moment": "2.29.1",
    "patch-package": "^6.4.7",
    "postcss-pxtorem": "^6.0.0",
    "remixicon": "^2.5.0",
    "vue": "^3.2.26",
    "vue-router": "4.0.11",
    "vuex": "^4.0.2",
    "web3": "1.6.0",
    "web3-eth": "1.6.0",
    "web3-eth-contract": "1.6.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.1",
    "@types/jest": "^26.0.22",
    "@types/lodash": "^4.14.176",
    "@types/node": "^16.11.6",
    "@types/uuid": "^8.3.1",
    "@typescript-eslint/eslint-plugin": "^4.21.0",
    "@typescript-eslint/parser": "^4.21.0",
    "@vitejs/plugin-vue": "1.9.4",
    "@vue/compiler-sfc": "3.2.26",
    "@vue/test-utils": "^2.0.0-rc.4",
    "commitizen": "^4.2.3",
    "cz-conventional-changelog": "^3.3.0",
    "cz-customizable": "^6.3.0",
    "eslint": "^7.24.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-import-resolver-node": "^0.3.6",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.3.5",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.8.0",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "stylus": "^0.54.8",
    "ts-jest": "^26.5.4",
    "ts-morph": "^12.2.0",
    "typescript": "^4.4.4",
    "unplugin-vue-components": "^0.17.0",
    "vite": "2.6.14",
    "vue-jest": "^5.0.0-alpha.7",
    "vue-tsc": "^0.3.0"
  }
