### ISSUE TITLE
[Bug Report] error in production mode

### ISSUE THREAD

**Issue by Archieeeeee** [element-plus/element-plus#4817]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows 11

### Vue version
3.2.26

### Reproduction Link
https://github.com/Archieeeeee/vitedemo

### Steps to reproduce
```
yarn
yarn run build 
yarn run preview
```

#then close the dialog and check the console output

### What is Expected?
no error

### What is actually happening?
```
console error:
vendor.8df8f3d4.js:4 ReferenceError: loginVisible is not defined
    at c.onUpdate:modelValue.t.<computed>.t.<computed> (main.d6779dc3.js:1:1069)
    at xn (vendor.8df8f3d4.js:4:656)
    at vn (vendor.8df8f3d4.js:4:735)
    at m1 (vendor.8df8f3d4.js:1:13200)
    at f (vendor.8df8f3d4.js:31:93795)
    at xn (vendor.8df8f3d4.js:4:656)
    at vn (vendor.8df8f3d4.js:4:735)
    at S (vendor.8df8f3d4.js:1:17513)
    at C._leaveCb (vendor.8df8f3d4.js:1:18084)
    at V (vendor.8df8f3d4.js:4:9729)
p$ @ vendor.8df8f3d4.js:4
Dr @ vendor.8df8f3d4.js:4
xn @ vendor.8df8f3d4.js:4
vn @ vendor.8df8f3d4.js:4
m1 @ vendor.8df8f3d4.js:1
f @ vendor.8df8f3d4.js:31
xn @ vendor.8df8f3d4.js:4
vn @ vendor.8df8f3d4.js:4
S @ vendor.8df8f3d4.js:1
C._leaveCb @ vendor.8df8f3d4.js:1
V @ vendor.8df8f3d4.js:4
H @ vendor.8df8f3d4.js:4
a @ vendor.8df8f3d4.js:4
d @ vendor.8df8f3d4.js:4
(anonymous) @ vendor.8df8f3d4.js:4
setTimeout (async)
_h @ vendor.8df8f3d4.js:4
(anonymous) @ vendor.8df8f3d4.js:4
requestAnimationFrame (async)
(anonymous) @ vendor.8df8f3d4.js:4
requestAnimationFrame (async)
Eh @ vendor.8df8f3d4.js:4
onLeave @ vendor.8df8f3d4.js:4
leave @ vendor.8df8f3d4.js:1
updated @ vendor.8df8f3d4.js:4
xn @ vendor.8df8f3d4.js:4
vn @ vendor.8df8f3d4.js:4
Ao @ vendor.8df8f3d4.js:1
(anonymous) @ vendor.8df8f3d4.js:1
dh @ vendor.8df8f3d4.js:4
fh @ vendor.8df8f3d4.js:4
Promise.then (async)
uh @ vendor.8df8f3d4.js:4
ch @ vendor.8df8f3d4.js:4
m$ @ vendor.8df8f3d4.js:4
m @ vendor.8df8f3d4.js:4
Di @ vendor.8df8f3d4.js:1
Hi @ vendor.8df8f3d4.js:1
set value @ vendor.8df8f3d4.js:1
w @ vendor.8df8f3d4.js:31
m @ vendor.8df8f3d4.js:31
g @ vendor.8df8f3d4.js:31
$ @ vendor.8df8f3d4.js:31
onClick @ vendor.8df8f3d4.js:17
D.onClick.t.<computed>.t.<computed> @ vendor.8df8f3d4.js:31
xn @ vendor.8df8f3d4.js:4
vn @ vendor.8df8f3d4.js:4
n @ vendor.8df8f3d4.js:4
```

**Comment by emojiiii** [comment]
I tried your `demo` and didn't find the problem you described

**Comment by Archieeeeee** [comment]
> 
dev模式正常，build之后，运行。
关掉对话框，控制台报错，你那里没报错吗

**Comment by emojiiii** [comment]
This is the problem of `vue3`. You can see the compiled code.

![impicture_20211214_093947](https://user-images.githubusercontent.com/30518686/145916995-7e48c093-8eaa-4d2d-ae00-27ca4a5d37bd.png)

**Comment by Archieeeeee** [comment]
thank you for your help and suggestion
