### ISSUE TITLE
[Bug Report] 单元测试中el-Select出现 Maximum recursive updates exceeded 异常

### ISSUE THREAD

**Issue by zxjingmin** [element-plus/element-plus#5170]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Ubuntu 21.10

### Vue version
3.2.26

### Reproduction Link
https://github.com/zxjingmin/vue3_next/tree/feature/dynamicForm

### Steps to reproduce
使用测试库
 "jest": "^27.4.6",
"@vue/test-utils": "^2.0.0-rc.18",
"vue3-jest": "27.0.0-alpha.2"

vue template: Dynamic.vue

<template lang="pug">
el-form(ref='DynamicForm', :model='formData', label-width='80px')
  el-form-item(v-for='item in formItem', :key='`input_${item.name}`' :label='item.label')
    el-input(v-if='item.type == "text"' v-model='formData[item.name]')
    el-select(v-if='item.type == "select"' 
      v-model='formData.address' 
      allow-create 
      default-first-option
      placeholder="select")
      el-option(value='open')
  el-form-item
    el-button(type='primary', @click='submitHandle') Submit
</template>

unit test:

const formItem: FormItemType[] = [
  {
    name: 'name',
    label: '姓名',
    type: 'text',
    default: 'jingmin',
  },
  {
    name: 'address',
    label: '地区',
    type: 'select',
    list: ['上海', '天津', '湖北'],
  },

];
describe('Dynamic.vue test', () => {
  
  test('test ', async () => {
    const wrapper = await mount(Dynamic, {
      global: {
        plugins: [store, elementPlus],
      },
      props: {
        formItem,
      },
    });
    await wrapper.find('button').trigger('click');
  });
});

### What is Expected?
单元测试无法通过，

### What is actually happening?
在浏览器中能正常使用，若没有select类型，，单元测试能通过，有select类型时报错如下

[Vue warn]: Maximum recursive updates exceeded in component <ElSelect>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

**Comment by zxjingmin** [comment]
ReferenceError: ResizeObserver is not defined

      at Object.addResizeListener (packages/utils/resize-event.ts:17:26)
      at packages/components/select/src/select-dropdown.vue:39:7
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
      at callWithAsyncErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
      at Array.hook.__weh.hook.__weh (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2657:29)
      at flushPostFlushCbs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:352:47)
      at render (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5575:9)

**Comment by zxjingmin** [comment]
这是是关键的错误

    ReferenceError: ResizeObserver is not defined

      at Object.addResizeListener (packages/utils/resize-event.ts:17:26)
      at packages/components/select/src/select-dropdown.vue:39:7
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
      at callWithAsyncErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
      at Array.hook.__weh.hook.__weh (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2657:29)
      at flushPostFlushCbs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:352:47)
      at render (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5575:9)

**Comment by sxzz** [comment]
@zxjingmin Please use `resize-observer-polyfill`.
https://github.com/element-plus/element-plus/blob/21e778b057816e88e84a100970e588ab76d9324a/jest.setup.js#L7
