### ISSUE TITLE
[Bug Report] 引用自定义组件文件名和ElementPlus内部组件名重名引起的栈溢出

### ISSUE THREAD

**Issue by whidy** [element-plus/element-plus#6116]
### Element Plus version
2.0.2

### OS/Browsers version
macOS 15 / Chrome 96

### Vue version
3.2.31

### Reproduction Link
https://codesandbox.io/s/filename-bug-qr3r80

### Steps to reproduce
1. created your own vue component named `El-Dialog.vue`
2. import `El-Dialog.vue` to any parent component, such as `import MyDialog from './components/El-Dialog.vue'` and use it in template as `<MyDialog></MyDialog>`
3. preview page and error report

------------------------

1. 创建一个自己的组件名称为`El-Dialog.vue`
2. 在任意父组件引入这个文件，组件变量名任意
3. 预览页面发生错误

### What is Expected?
Code runs well in version 1.20-beta3, no error founded, it might not a bug, I am not sure.

------------------------

页面显示正常，当然也许这不是个BUG，但是旧版比如1.20beta-3不存在此问题

### What is actually happening?
出现错误信息：

------------------------

Error messages below:

```
[Vue warn]: Extraneous non-props attributes (modelValue, title, width, before-close) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
  at <ElDialog> 
  at <ElConfigProvider size="small" zIndex=3000 > 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
renderComponentRoot @ runtime-core.esm-bundler.js:968
componentUpdateFn @ runtime-core.esm-bundler.js:5030
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
render2 @ runtime-core.esm-bundler.js:5641
mount @ runtime-core.esm-bundler.js:3877
app.mount @ runtime-dom.esm-bundler.js:1590
(anonymous) @ main.ts:4
Show 9 more frames
runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-props attributes (modelValue, title, width, before-close) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
  at <ElDialog> 
  at <ElConfigProvider size="small" zIndex=3000 > 
  at <App>
....
....
....
[Vue warn]: Extraneous non-props attributes (modelValue, title, width, before-close) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
  at <ElDialog modelValue=false onUpdate:modelValue=fn title="Tips"  ... > 
....
....
....
Uncaught RangeError: Maximum call stack size exceeded
    at warn2 (runtime-core.esm-bundler.js:36:22)
    at renderComponentRoot (runtime-core.esm-bundler.js:968:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5030:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at setupRenderEffect (runtime-core.esm-bundler.js:5156:9)
    at mountComponent (runtime-core.esm-bundler.js:4939:9)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at mountChildren (runtime-core.esm-bundler.js:4685:13)
    at processFragment (runtime-core.esm-bundler.js:4856:13)
```

**Comment by whidy** [comment]
Related detail article by me: [filename-cause-stack-exceeds](https://github.com/whidy/Oh-Bugs/tree/filename-cause-stack-exceeds)

**Comment by emojiiii** [comment]
你可以尝试把内部的 `setup` 语法糖去掉吗？然后用 `defineComponent` 声明，加上 `name` 属性，名称可以改为 `myDialog`尝试一下。 @whidy

**Comment by whidy** [comment]
> 你可以尝试把内部的 `setup` 语法糖去掉吗？然后用 `defineComponent` 声明，加上 `name` 属性，名称可以改为 `myDialog`尝试一下。 @whidy

试了下不起作用，[示例](https://codesandbox.io/s/try-to-fix-k3bre3)

**Comment by a1067111756** [comment]
这是unplugin-vue-components导致的，它自动导入靠的就是识别组件名EL开头来确定是Element的组件

**Comment by whidy** [comment]
> 这是unplugin-vue-components导致的，它自动导入靠的就是识别组件名EL开头来确定是Element的组件

我试了下，确实全局没有出现问题，我去看看这个按需引入的细节，不过确实在升级前，貌似按需引入的方式和后来的正式版是有区别的。
