### ISSUE TITLE
[Bug Report] [Component] [table] unmounted(): Cannot read properties of null (reading 'wrap$')

### ISSUE THREAD

**Issue by YeKelvin** [element-plus/element-plus#6692]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Steps to reproduce

el-table unmounted()

### What is Expected?

Close normally without error

### What is actually happening?

TypeError: Cannot read properties of null (reading 'wrap$')
    at unbindEvents (style-helper.ts:171:35)
    at style-helper.ts:167:5
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2667:29)
    at invokeArrayFns (shared.esm-bundler.js:556:13)
    at unmountComponent (runtime-core.esm-bundler.js:5584:13)
    at unmount (runtime-core.esm-bundler.js:5494:13)
    at unmountChildren (runtime-core.esm-bundler.js:5622:13)
    at unmount (runtime-core.esm-bundler.js:5512:17)

**Comment by Dsaquel** [comment]
Should be fixed in newer versions.

Feel free to reopen if it not.
