### ISSUE TITLE
[Bug Report] 运行pnpm dev 报错

### ISSUE THREAD

**Issue by ChenAdien** [element-plus/element-plus#6740]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/tree/dev/play)

### Steps to reproduce

执行dev命令

### What is Expected?

正常打开

### What is actually happening?

报错

### Additional comments

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js:3717:17)
    at Proxy._sfc_render (App.vue:9:20)
    at renderComponentRoot (runtime-core.esm-bundler.js:893:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5030:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at setupRenderEffect (runtime-core.esm-bundler.js:5156:9)
    at mountComponent (runtime-core.esm-bundler.js:4939:9)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at render2 (runtime-core.esm-bundler.js:5641:13)

**Comment by alex1504** [comment]
同样遇到了，安装完成后pnpm dev执行报错

**Comment by ChenAdien** [comment]
> 同样遇到了，安装完成后pnpm dev执行报错

删掉app.vue里面的v-loading就好了

**Comment by Eviwang** [comment]
> 

不报错了，但是样式不生效，组件也没有生效。
