### ISSUE TITLE
[Component] [table-v2, date-picker] [Component][el-table-v2][el-date-picker]在el-table-v2 中使用  ElDatePicker 做自定义元素时无法获得选中的值  并且控制台会报错

### ISSUE THREAD

**Issue by kuaifengle** [element-plus/element-plus#8520]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.6`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-table-v2`
- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiA0MDBweFwiPlxuICAgIDxlbC1hdXRvLXJlc2l6ZXI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IGhlaWdodCwgd2lkdGggfVwiPlxuICAgICAgICA8ZWwtdGFibGUtdjIgOmNvbHVtbnM9XCJjb2x1bW5zXCIgOmRhdGE9XCJkYXRhXCIgOndpZHRoPVwid2lkdGhcIiA6aGVpZ2h0PVwiaGVpZ2h0XCIgZml4ZWQgLz5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1hdXRvLXJlc2l6ZXI+XG4gIDwvZGl2PlxuXG4gIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwidmFsdWVcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmLCB0b1JlZnMsIG9uTW91bnRlZCwgaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsRGF0ZVBpY2tlcixFbElucHV0IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIG5hbWU6ICd0YWJsZVYyJyxcbiAgc2V0dXAoKSB7XG4gICAgb25Nb3VudGVkKCgpID0+IHt9KVxuXG4gICAgbGV0IHRhYmxlRGF0YSA9IHJlYWN0aXZlKHtcbiAgICAgIGRhdGE6IFtcbiAgICAgICAge1xuICAgICAgICAgIHRleHQ6ICdxaWV1cm9xdXdlb3InLFxuICAgICAgICAgIHRleHRFZGl0OiBmYWxzZSxcbiAgICAgICAgICBuYW1lOiAnMTIzMTIzJyxcbiAgICAgICAgICBuYW1lRWRpdDogZmFsc2UsXG4gICAgICAgICAgYWdlOiAwLFxuICAgICAgICAgIGFnZUVkaXQ6IGZhbHNlLFxuICAgICAgICAgIHNleDogJycsXG4gICAgICAgICAgc2V4RWRpdDogZmFsc2UsXG4gICAgICAgICAgbGlrZTogW10sXG4gICAgICAgICAgbGlrZUVkaXQ6IGZhbHNlLFxuICAgICAgICAgIHdvcms6ICcnLFxuICAgICAgICAgIHdvcmtFZGl0OiBmYWxzZSxcbiAgICAgICAgICB1c2VyTmFtZTogJycsXG4gICAgICAgICAgdXNlck5hbWVFZGl0OiBmYWxzZSxcbiAgICAgICAgICBwYXNzd29yZDogJycsXG4gICAgICAgICAgcGFzc3dvcmRFZGl0OiBmYWxzZSxcbiAgICAgICAgICBiaXJ0aGRheTogJycsXG4gICAgICAgICAgYmlydGhkYXlFZGl0OiBmYWxzZSxcbiAgICAgICAgICBjcmVhdGVUaW1lOiAnJyxcbiAgICAgICAgICBjcmVhdGVUaW1lRWRpdDogZmFsc2UsXG4gICAgICAgICAgbGVhdmVUaW1lOiAnJyxcbiAgICAgICAgICBsZWF2ZVRpbWVFZGl0OiBmYWxzZVxuICAgICAgICB9XG4gICAgICBdLFxuICAgICAgY29sdW1uc1R5cGVPYmplY3Q6IHtcbiAgICAgICAgdGV4dDoge1xuICAgICAgICAgIHRpdGxlOiAn5paH5pysJyxcbiAgICAgICAgICB0eXBlOiAnVGV4dCcsXG4gICAgICAgICAgd2lkdGg6IDIwMFxuICAgICAgICB9LFxuICAgICAgICBuYW1lOiB7XG4gICAgICAgICAgdGl0bGU6ICflkI3np7AnLFxuICAgICAgICAgIHR5cGU6ICdJbnB1dCcsXG4gICAgICAgICAgd2lkdGg6IDQwMFxuICAgICAgICB9LFxuICAgICAgICBiaXJ0aGRheToge1xuICAgICAgICAgIHRpdGxlOiAn55Sf5pelJyxcbiAgICAgICAgICB0eXBlOiAnRGF0ZVBpY2tlcidcbiAgICAgICAgfSxcbiAgICAgIH0sXG4gICAgICBjb2x1bW5zOiBbXSxcbiAgICAgIGluaXQoKSB7XG4gICAgICAgIGxldCBhcnIgPSBPYmplY3Qua2V5cyh0YWJsZURhdGEuY29sdW1uc1R5cGVPYmplY3QpXG4gICAgICAgIGxldCBjb2x1bW5zID0gW11cbiAgICAgICAgYXJyLmZvckVhY2goKGtleSwgaW5kZXgpID0+IHtcbiAgICAgICAgICBsZXQgaXRlbSA9IHRhYmxlRGF0YS5jb2x1bW5zVHlwZU9iamVjdFtrZXldXG4gICAgICAgICAgbGV0IGRlZmF1bHRSb3dJdGVtID0ge1xuICAgICAgICAgICAga2V5OiAnY29sdW1uLScgKyBpbmRleCxcbiAgICAgICAgICAgIGRhdGFLZXk6IGtleSxcbiAgICAgICAgICAgIHRpdGxlOiBpdGVtLnRpdGxlLFxuICAgICAgICAgICAgd2lkdGg6IGl0ZW0ud2lkdGggfHwgMjAwXG4gICAgICAgICAgfVxuXG4gICAgICAgICAgY29sdW1uc1tpbmRleF0gPSBkZWZhdWx0Um93SXRlbVxuICAgICAgICAgIHN3aXRjaCAoaXRlbS50eXBlKSB7XG4gICAgICAgICAgICBjYXNlICdUZXh0JzpcbiAgICAgICAgICAgICAgY29sdW1uc1tpbmRleF0gPSBkZWZhdWx0Um93SXRlbVxuICAgICAgICAgICAgICBicmVha1xuICAgICAgICAgICAgY2FzZSAnSW5wdXQnOlxuICAgICAgICAgICAgICAgICBjb2x1bW5zW2luZGV4XVsnY2VsbFJlbmRlcmVyJ10gPSAoeyByb3dEYXRhLCBjb2x1bW4gfSkgPT5cbiAgICAgICAgICAgICAgICBoKEVsSW5wdXQsIHtcbiAgICAgICAgICAgICAgICAgIG1vZGVsVmFsdWU6IHJvd0RhdGFbY29sdW1uLmRhdGFLZXldLFxuICAgICAgICAgICAgICAgIH0pXG4gICAgICAgICAgICAgIGJyZWFrXG4gICAgICAgICAgIGNhc2UgJ0RhdGVQaWNrZXInOlxuICAgICAgICAgICAgICBjb2x1bW5zW2luZGV4XVsnY2VsbFJlbmRlcmVyJ10gPSAoeyByb3dEYXRhLCBjb2x1bW4gfSkgPT5cbiAgICAgICAgICAgICAgICBoKEVsRGF0ZVBpY2tlciwge1xuICAgICAgICAgICAgICAgICAgbW9kZWxWYWx1ZTogcm93RGF0YVtjb2x1bW4uZGF0YUtleV1cbiAgICAgICAgICAgICAgICB9KVxuICAgICAgICAgICAgICBicmVha1xuICAgICAgICAgIH1cblxuICAgICAgICAgIGlmIChpbmRleCA9PT0gYXJyLmxlbmd0aCAtIDEpIHtcbiAgICAgICAgICAgIHRhYmxlRGF0YS5jb2x1bW5zID0gY29sdW1uc1xuICAgICAgICAgICAgY29uc29sZS5sb2coY29sdW1ucylcbiAgICAgICAgICB9XG4gICAgICAgIH0pXG4gICAgICB9XG4gICAgfSlcbiAgICB0YWJsZURhdGEuaW5pdCgpXG5cbiAgICBsZXQgdmFsdWUgPSByZWYoJycpXG4gICAgcmV0dXJuIHtcbiAgICAgIC4uLnRvUmVmcyh0YWJsZURhdGEpLFxuICAgICAgdmFsdWVcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4udGFibGUtdjItaW5saW5lLWVkaXRpbmctdHJpZ2dlciB7XG4gIGJvcmRlcjogMXB4IHRyYW5zcGFyZW50IGRvdHRlZDtcbiAgd2lkdGg6IDEwMCU7XG4gIGxpbmUtaGVpZ2h0OiAzMnB4O1xuICBwYWRkaW5nOiAwIDEwcHg7XG4gIG1pbi1oZWlnaHQ6IDMycHg7XG59XG5cbi50YWJsZS12Mi1pbmxpbmUtZWRpdGluZy10cmlnZ2VyOmhvdmVyIHtcbiAgYm9yZGVyLWNvbG9yOiB2YXIoLS1lbC1jb2xvci1wcmltYXJ5KTtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在el-table-v2 中使用自定义元素 [el-date-picker] 可以正常显示元素  ==> 但是操作选择时间后控制台会报错 

报错信息
```
_objectToString.js:3 Uncaught RangeError: Maximum call stack size exceeded.
    at W (_objectToString.js:3:32)
    at callWithErrorHandling (runtime-dom.esm-browser.js:1651:22)
    at callWithAsyncErrorHandling (runtime-dom.esm-browser.js:1660:21)
    at emit$1 (runtime-dom.esm-browser.js:2210:9)
    at runtime-dom.esm-browser.js:8724:53
    at HTMLDivElement.c (_objectToString.js:3:32)
    at W (_objectToString.js:3:32)
    at callWithErrorHandling (runtime-dom.esm-browser.js:1651:22)
    at callWithAsyncErrorHandling (runtime-dom.esm-browser.js:1660:21)
    at emit$1 (runtime-dom.esm-browser.js:2210:9)
```

### What is Expected?

期望 el-date-picker时间选择器能在 el-table-v2虚拟表格中正确返回选择时间

### What is actually happening?

```
_objectToString.js:3 Uncaught RangeError: Maximum call stack size exceeded.
    at W (_objectToString.js:3:32)
    at callWithErrorHandling (runtime-dom.esm-browser.js:1651:22)
    at callWithAsyncErrorHandling (runtime-dom.esm-browser.js:1660:21)
    at emit$1 (runtime-dom.esm-browser.js:2210:9)
    at runtime-dom.esm-browser.js:8724:53
    at HTMLDivElement.c (_objectToString.js:3:32)
    at W (_objectToString.js:3:32)
    at callWithErrorHandling (runtime-dom.esm-browser.js:1651:22)
    at callWithAsyncErrorHandling (runtime-dom.esm-browser.js:1660:21)
    at emit$1 (runtime-dom.esm-browser.js:2210:9)
```

### Additional comments

_(empty)_

**Comment by kuaifengle** [comment]
![image](https://user-images.githubusercontent.com/24524172/176156798-cdbc06b7-c528-415c-b252-8c81eb8b6ee8.png)
补充图片
