### ISSUE TITLE
[Component] [loading, table] Vite 3.0.0 + Vue + TS

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [element-plus/element-plus#8813]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome/103.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-loading`
- `el-table`

### Reproduction Link

[Github Repo](https://github.com/xuxiaowei-com-cn/my-vue-app)

### Steps to reproduce

在 el-table 中使用 v-loading 后，控制台出现错误：
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js:2764:17)
    at UserView.vue:76:16
    at Proxy.renderFnWithContext (runtime-core.esm-bundler.js:853:21)
    at ReactiveEffect.fn (container.vue:31:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at get value [as value] (reactivity.esm-bundler.js:1144:39)
    at unref (reactivity.esm-bundler.js:1052:29)
    at Proxy.<anonymous> (container.vue:39:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5580:57)
withDirectives @ runtime-core.esm-bundler.js:2764
（匿名） @ UserView.vue:76
renderFnWithContext @ runtime-core.esm-bundler.js:853
（匿名） @ container.vue:31
run @ reactivity.esm-bundler.js:185
get value @ reactivity.esm-bundler.js:1144
unref @ reactivity.esm-bundler.js:1052
（匿名） @ container.vue:39
renderComponentRoot @ runtime-core.esm-bundler.js:896
componentUpdateFn @ runtime-core.esm-bundler.js:5580
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5694
setupRenderEffect @ runtime-core.esm-bundler.js:5708
mountComponent @ runtime-core.esm-bundler.js:5490
processComponent @ runtime-core.esm-bundler.js:5448
patch @ runtime-core.esm-bundler.js:5038
mountChildren @ runtime-core.esm-bundler.js:5234
processFragment @ runtime-core.esm-bundler.js:5407
patch @ runtime-core.esm-bundler.js:5031
componentUpdateFn @ runtime-core.esm-bundler.js:5587
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5694
setupRenderEffect @ runtime-core.esm-bundler.js:5708
mountComponent @ runtime-core.esm-bundler.js:5490
processComponent @ runtime-core.esm-bundler.js:5448
patch @ runtime-core.esm-bundler.js:5038
componentUpdateFn @ runtime-core.esm-bundler.js:5660
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5694
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:396
Promise.catch（异步）
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2687
flushPostFlushCbs @ runtime-core.esm-bundler.js:358
flushJobs @ runtime-core.esm-bundler.js:403
Promise.then（异步）
queueFlush @ runtime-core.esm-bundler.js:285
queueCb @ runtime-core.esm-bundler.js:307
queuePostFlushCb @ runtime-core.esm-bundler.js:313
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1582
scheduler @ runtime-core.esm-bundler.js:1804
triggerEffect @ reactivity.esm-bundler.js:394
triggerEffects @ reactivity.esm-bundler.js:384
triggerRefValue @ reactivity.esm-bundler.js:1000
（匿名） @ reactivity.esm-bundler.js:1131
triggerEffect @ reactivity.esm-bundler.js:394
triggerEffects @ reactivity.esm-bundler.js:379
triggerRefValue @ reactivity.esm-bundler.js:1000
（匿名） @ reactivity.esm-bundler.js:1131
triggerEffect @ reactivity.esm-bundler.js:394
triggerEffects @ reactivity.esm-bundler.js:379
triggerRefValue @ reactivity.esm-bundler.js:1000
set value @ reactivity.esm-bundler.js:1044
finalizeNavigation @ vue-router.mjs:3307
（匿名） @ vue-router.mjs:3180
Promise.then（异步）
pushWithRedirect @ vue-router.mjs:3151
push @ vue-router.mjs:3078
handleMenuItemClick @ menu.ts:132
handleClick @ menu-item.vue:89
createElementBlock.onClick._cache.<computed>._cache.<computed> @ menu-item.vue:10
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
```

### What is Expected?

可以在 Vite 3.0.0 中，正常使用 el-table、v-loading

### What is actually happening?

在 Vite 3.0.0 中，正常使用 el-table、v-loading 中报错

### Additional comments

_(empty)_

**Comment by xuxiaowei-com-cn** [comment]
直接运行上述仓库的项目就可复现错误。
移除 v-loading="loading" 即可正常启动。

**Comment by holazz** [comment]
Maybe you need to remove `"type": "module"` from `package.json`.

**Comment by xuxiaowei-com-cn** [comment]
> 删除 `package.json` 中的 `"type": "module"`。
谢谢，已解决

**Comment by crissscifo** [comment]
删除 package.json 中的 "type": "module"
项目启动会报其他错误😥

**Comment by crissscifo** [comment]
error when starting dev server:
Error: Cannot find module 'node:path'
