### ISSUE TITLE
[Build] @element-plus/constants: Not found

### ISSUE THREAD

**Issue by majidzeno** [element-plus/element-plus#8988]
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.0`
- Element Plus Version: `2.2.10`
- Browser / OS: `macOS 12.4`
- Build Tool: `Other`

### Related Component

- `N/A`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/notanexample)

### Steps to reproduce

I'm trying to setup elements-plus locally, I'm using node -> v16.14.2, yarn -> 1.22.18
Steps: 
- yarn install
- //choose 0.0.5
I got an error
'error An unexpected error occurred: "https://registry.yarnpkg.com/@element-plus%2fconstants: Not found".'

### What is Expected?

Installing successfully

### What is actually happening?

error An unexpected error occurred: "https://registry.yarnpkg.com/@element-plus%2fconstants: Not found".

### Additional comments

N/A

![Screen Shot 2022-07-23 at 8 13 34 PM](https://user-images.githubusercontent.com/18016774/180617795-cb5385a6-5db2-4660-b7e3-71500421d755.png)

**Comment by btea** [comment]
Can you provide a reproduction link?

**Comment by majidzeno** [comment]
@btea How I should provide the reproduction link ? this is failing on my machine 🤔

**Comment by btea** [comment]
Maybe you can provide a valid repository link.

**Comment by majidzeno** [comment]
No repo, I was trying to install elements-plus locally when I got this error, I will close this for now I will try again with the latest updates of `elements-plus`, If this happened again I will re-open this 🙏 
@btea Appreciate your help, thanks 🙏

**Comment by btea** [comment]
Ok. 😄

**Comment by PLQin** [comment]
I also encountered the same problem, under the window system, execute the install command, an exception occurs: 
 
 ```
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\yarn\bin\yarn.js

PATH: 
  C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Users\qingg\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Users\qingg\AppData\Local\Microsoft\WindowsApps;D:\Install\Microsoft VS Code\bin;D:\Install\JetBrains\IntelliJ IDEA 2023.1\bin;;C:\Users\qingg\AppData\Roaming\nvm;C:\Program Files\nodejs

Yarn version: 
  1.22.19

Node version: 
  18.16.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@element-plus%2fconstants: Not found
      at params.callback [as _callback] (C:\Users\qingg\AppData\Roaming\nvm\v18.16.0\node_modules\yarn\lib\cli.js:66145:18)
      at self.callback (C:\Users\qingg\AppData\Roaming\nvm\v18.16.0\node_modules\yarn\lib\cli.js:140890:22)
      at Request.emit (node:events:513:28)
      at Request.<anonymous> (C:\Users\qingg\AppData\Roaming\nvm\v18.16.0\node_modules\yarn\lib\cli.js:141862:10)
      at Request.emit (node:events:513:28)
      at IncomingMessage.<anonymous> (C:\Users\qingg\AppData\Roaming\nvm\v18.16.0\node_modules\yarn\lib\cli.js:141784:12)
      at Object.onceWrapper (node:events:627:28)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

npm manifest: 
  {
    "name": "@element-plus/docs",
    "private": true,
    "scripts": {
      "dev": "pnpm gen-locale && vitepress dev .",
      "build": "NODE_ENV=production && vitepress build . && tsx .vitepress/build/rebuild-pwa.ts",
      "serve": "NODE_ENV=production vitepress serve . --port 5001",
      "gen-locale": "rimraf .vitepress/i18n && tsx .vitepress/build/crowdin-generate.ts",
      "crowdin-credentials": "tsx .vitepress/build/crowdin-credentials.ts"
    },
    "dependencies": {
      "@docsearch/js": "^3.1.0",
      "@element-plus/icons-vue": "^2.0.9",
      "@element-plus/metadata": "workspace:*",
      "@vue/shared": "^3.2.37",
      "@vueuse/core": "^9.1.0",
      "axios": "^0.27.2",
      "clipboard-copy": "^4.0.1",
      "element-plus": "npm:element-plus@latest",
      "markdown-it": "^13.0.1",
      "normalize.css": "^8.0.1",
      "nprogress": "^0.2.0",
      "prism-theme-vars": "^0.2.3",
      "vue": "^3.2.37"
    },
    "devDependencies": {
      "@crowdin/cli": "^3.7.8",
      "@docsearch/react": "^3.1.0",
      "@element-plus/build": "workspace:*",
      "@element-plus/build-constants": "workspace:*",
      "@element-plus/build-utils": "workspace:*",
      "@iconify-json/ri": "^1.1.3",
      "@types/markdown-it": "^12.2.3",
      "@vitejs/plugin-vue-jsx": "^1.3.10",
      "chalk": "^4.1.2",
      "consola": "^2.15.3",
      "escape-html": "^1.0.3",
      "fast-glob": "^3.2.11",
      "markdown-it-container": "^3.0.0",
      "octokit": "^2.0.3",
      "prismjs": "^1.28.0",
      "unocss": "0.33.5",
      "unplugin-icons": "^0.14.6",
      "unplugin-vue-components": "^0.20.1",
      "unplugin-vue-macros": "^0.11.2",
      "vite": "^2.9.15",
      "vite-plugin-inspect": "^0.5.0",
      "vite-plugin-mkcert": "^1.7.2",
      "vite-plugin-pwa": "^0.12.0",
      "vitepress": "^0.22.4"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
 ```

**Comment by btea** [comment]
@PLQin Directly clone the source code, and then execute the `yarn install` error?

**Comment by PLQin** [comment]
> @PLQin Directly clone the source code, and then execute the `yarn install` error?

yes！

**Comment by PLQin** [comment]
If using Mac and executing install under version 3.0, then:

```
Arguments: 
  /Users/a1234/.nvm/versions/node/v18.14.1/bin/node /Users/a1234/.nvm/versions/node/v18.14.1/bin/yarn

PATH: 
  /Users/a1234/.nvm/versions/node/v18.14.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/a1234/.nvm/versions/node/v18.14.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin

Yarn version: 
  1.22.19

Node version: 
  18.14.1

Platform: 
  darwin arm64

Trace: 
  Error: https://registry.yarnpkg.com/@element-plus%2fcli: Not found
      at params.callback [as _callback] (/Users/a1234/.nvm/versions/node/v18.14.1/lib/node_modules/yarn/lib/cli.js:66145:18)
      at self.callback (/Users/a1234/.nvm/versions/node/v18.14.1/lib/node_modules/yarn/lib/cli.js:140890:22)
      at Request.emit (node:events:513:28)
      at Request.<anonymous> (/Users/a1234/.nvm/versions/node/v18.14.1/lib/node_modules/yarn/lib/cli.js:141862:10)
      at Request.emit (node:events:513:28)
      at IncomingMessage.<anonymous> (/Users/a1234/.nvm/versions/node/v18.14.1/lib/node_modules/yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:627:28)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

npm manifest: 
  {
    "private": true,
    "packageManager": "pnpm@7.3.0",
    "scripts": {
      "cz": "czg",
      "test": "vitest",
      "test:coverage": "vitest --coverage",
      "test:ssr": "vitest --config ./ssr-testing/vitest.config.ts",
      "prepare:e2e": "if [ ! -d \"docs/.vitepress/dist\" ]; then pnpm run docs:build; fi;",
      "dev": "pnpm -C play dev",
      "gen": "bash ./scripts/gc.sh",
      "diff:table": "tsx scripts/build-table.ts",
      "update:version": "tsx scripts/update-version.ts",
      "clean": "pnpm run clean:dist && pnpm run -r --parallel clean",
      "clean:dist": "rimraf dist",
      "build": "pnpm run -C internal/build start",
      "build:node": "pnpm run --filter \"./packages/node/*\" --stream build",
      "build:theme": "pnpm run -C packages/web/theme-chalk build",
      "format": "prettier --write --cache .",
      "lint": "eslint . --ext .vue,.js,.ts,.jsx,.tsx,.md,.json --max-warnings 0 --cache",
      "lint:fix": "pnpm run lint --fix",
      "lint:commit": "commitlint --from $(git merge-base origin/dev HEAD) --to HEAD > ./commit-lint.txt",
      "typecheck": "run-p typecheck:web typecheck:node typecheck:vite-config typecheck:vitest",
      "typecheck:web": "vue-tsc -p tsconfig.web.json --composite false --noEmit",
      "typecheck:node": "tsc -p tsconfig.node.json --noEmit",
      "typecheck:play": "vue-tsc -p tsconfig.play.json --composite false --noEmit",
      "typecheck:vite-config": "vue-tsc -p tsconfig.vite-config.json --composite false --noEmit",
      "typecheck:vitest": "vue-tsc -p tsconfig.vitest.json --composite false --noEmit",
      "docs:dev": "pnpm run -C docs dev",
      "docs:build": "pnpm run -C docs build",
      "docs:serve": "pnpm run -C docs serve",
      "docs:gen-locale": "pnpm run -C docs gen-locale",
      "docs:crowdin-credentials": "pnpm run -C docs crowdin-credentials",
      "stub": "pnpm run -r --parallel stub",
      "prepare": "husky install"
    },
    "peerDependencies": {
      "vue": "^3.2.0"
    },
    "dependencies": {
      "@element-plus/build-published": "npm:@element-plus-next/build@3.0.0-alpha.3",
      "@element-plus/cli": "workspace:*",
      "@element-plus/components": "workspace:*",
      "@element-plus/constants": "workspace:*",
      "@element-plus/hooks": "workspace:*",
      "@element-plus/icons-vue": "^2.0.6",
      "@element-plus/locale": "workspace:*",
      "@element-plus/test-utils": "workspace:*",
      "@element-plus/theme-chalk": "workspace:*",
      "@element-plus/tokens": "workspace:*",
      "@element-plus/utils": "workspace:*",
      "@element-plus/vue-directives": "workspace:*",
      "@floating-ui/dom": "^1.0.1",
      "@popperjs/core": "npm:@sxzz/popperjs-es@^2.11.7",
      "@types/lodash": "^4.14.182",
      "@types/lodash-es": "^4.17.6",
      "@vueuse/core": "^9.1.0",
      "async-validator": "^4.2.5",
      "dayjs": "^1.11.3",
      "escape-html": "^1.0.3",
      "lodash": "^4.17.21",
      "lodash-es": "^4.17.21",
      "lodash-unified": "^1.0.2",
      "memoize-one": "^6.0.0",
      "normalize-wheel-es": "^1.2.0"
    },
    "devDependencies": {
      "@commitlint/cli": "^17.0.3",
      "@commitlint/config-conventional": "^17.0.3",
      "@element-plus/build": "workspace:^0.0.1",
      "@element-plus/build-published": "npm:@element-plus-next/build@3.0.0-alpha.3",
      "@element-plus/build-utils": "workspace:^0.0.1",
      "@element-plus/eslint-config": "workspace:*",
      "@element-plus/tsconfig": "workspace:*",
      "@esbuild-kit/cjs-loader": "^2.2.1",
      "@pnpm/find-workspace-packages": "^4.0.16",
      "@pnpm/logger": "^4.0.0",
      "@pnpm/types": "^8.4.0",
      "@rollup/plugin-json": "^4.1.0",
      "@types/fs-extra": "^9.0.13",
      "@types/gulp": "^4.0.9",
      "@types/jsdom": "^16.2.14",
      "@types/node": "*",
      "@types/sass": "^1.43.1",
      "@vitejs/plugin-vue": "^2.3.3",
      "@vitejs/plugin-vue-jsx": "^1.3.10",
      "@vitest/ui": "0.16.0",
      "@vue/test-utils": "^2.0.0",
      "@vue/tsconfig": "^0.1.3",
      "c8": "^7.11.3",
      "chalk": "^5.0.1",
      "consola": "^2.15.3",
      "csstype": "^2.6.20",
      "cz-git": "^1.3.8",
      "czg": "^1.3.8",
      "eslint": "^8.18.0",
      "eslint-define-config": "^1.5.1",
      "expect-type": "^0.13.0",
      "fast-glob": "^3.2.11",
      "husky": "^8.0.1",
      "jsdom": "16.4.0",
      "lint-staged": "^13.0.3",
      "npm-run-all": "^4.1.5",
      "prettier": "^2.7.1",
      "puppeteer": "^17.1.3",
      "resize-observer-polyfill": "^1.5.1",
      "rimraf": "^3.0.2",
      "sass": "^1.53.0",
      "ts-morph": "^14.0.0",
      "tsx": "^3.6.0",
      "type-fest": "^2.14.0",
      "typescript": "^4.7.4",
      "unplugin-element-plus": "^0.4.0",
      "unplugin-vue-define-options": "^0.6.1",
      "vite": "^3.1.0",
      "vitest": "0.12.6",
      "vue": "^3.2.37",
      "vue-router": "^4.0.16",
      "vue-tsc": "^0.38.2"
    },
    "engines": {
      "node": ">= 16"
    },
    "config": {
      "commitizen": {
        "path": "./node_modules/cz-git"
      }
    },
    "pnpm": {
      "peerDependencyRules": {
        "ignoreMissing": [
          "vite",
          "react",
          "react-dom"
        ]
      }
    },
    "lint-staged": {
      "*.{vue,js,ts,jsx,tsx,md,json}": "eslint --fix"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

```

**Comment by btea** [comment]
You should use `pnpm`, some internal packages use the workspace protocol.
https://github.com/element-plus/element-plus/blob/5cd6d614000c594dc2866271802cea832dabb525/package.json#L47-L50

**Comment by PLQin** [comment]
Thanks for the tip!  After executing pnpm, install is successful, but an error is reported when executing `pnpm run docs:serve`: 
 
```
$ pnpm run docs:build

> @ docs:build E:\element\element-plus-3.0\element-plus-3.0
> pnpm run -C docs build


> @element-plus/docs@ build E:\element\element-plus-3.0\element-plus-3.0\docs
> NODE_ENV=production && vitepress build . && tsx .vitepress/build/rebuild-pwa.ts

vitepress v0.22.4
X [ERROR] Could not resolve "../i18n/pages/sidebar.json"

    .vitepress/config/nav.ts:2:22:
      2 │ import navLocale from '../i18n/pages/sidebar.json'
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../i18n/pages/guide.json"

    .vitepress/config/sidebars.ts:2:24:
      2 │ import guideLocale from '../i18n/pages/guide.json'
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../i18n/pages/component.json"

    .vitepress/config/sidebars.ts:3:28:
      3 │ import componentLocale from '../i18n/pages/component.json'
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from E:\element\element-plus-3.0\element-plus-3.0\docs\.vitepress\config.mts
build error:
 Error: Build failed with 3 errors:
.vitepress/config/nav.ts:2:22: ERROR: Could not resolve "../i18n/pages/sidebar.json"
.vitepress/config/sidebars.ts:2:24: ERROR: Could not resolve "../i18n/pages/guide.json"
.vitepress/config/sidebars.ts:3:28: ERROR: Could not resolve "../i18n/pages/component.json"
    at failureErrorWithLog (E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:1605:15)
    at E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:1249:7)
    at E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:1358:14
    at E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (E:\element\element-plus-3.0\element-plus-3.0\node_modules\.pnpm\esbuild@0.14.47\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../i18n/pages/sidebar.json"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../i18n/pages/guide.json"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../i18n/pages/component.json"'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by PLQin** [comment]
The above problem can be solved by simply executing the command `pnpm run docs:gen-locale`
