### ISSUE TITLE
[Component] [date-picker] 日期选择器bug问题

### ISSUE THREAD

**Issue by tomato-sandwich** [element-plus/element-plus#9040]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/date-picker.html)

### Steps to reproduce

项目和官网上的date-picker组件（官网第一个示例），当前日期是2022-7-27，首次打开组件下拉日历面板、不切换月份直接选择面板中其他月份的日期时（如6月28日、8月3日），组件会出现异常，控制台输出错误且日期框被填入了错误的值。

控制台输出错误：
app.f9b59590.js:12 
       Uncaught RangeError: Maximum call stack size exceeded.
    at K (app.f9b59590.js:12:45652)
    at Fr (app.f9b59590.js:4:656)
    at Go (app.f9b59590.js:4:735)
    at nw (app.f9b59590.js:4:2791)
    at HTMLDivElement.u (app.f9b59590.js:12:41622)
    at K (app.f9b59590.js:12:45652)
    at Fr (app.f9b59590.js:4:656)
    at Go (app.f9b59590.js:4:735)
    at nw (app.f9b59590.js:4:2791)
    at HTMLDivElement.u (app.f9b59590.js:12:41622)

### What is Expected?

正确值，且无异常。

### What is actually happening?

值有误且出现异常。

### Additional comments

_(empty)_

**Comment by holazz** [comment]
已经修复了 #8588，升级 Element Plus 到最新版本。

**Comment by xiaoxian521** [comment]
It has been fixed, please wait for the next release
