### ISSUE TITLE
[install]  依赖包出错

### ISSUE THREAD

**Issue by chenweihan** [element-plus/element-plus#9546]
Bug Type: **`Build`**

## Environment
-  win10
-  node v16.15.0
-  npm v8.18.0
- Vue Version: `3.2.37`
- Element Plus Version: `2.2.15`
- Browser / OS: `拉依赖不成功`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Link](暂无)

### Steps to reproduce

使用vue3官网执行命令：
npm init vue@latest
创建一个初始项目
然后在安装element-plus 

cnpm install element-plus --save
× Install fail! Error: Unsupported URL Type: npm:@sxzz/popperjs-es@^2.11.7
Error: Unsupported URL Type: npm:@sxzz/popperjs-es@^2.11.7
    at parseUrl (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm-package-arg\npa.js:186:13)
    at npa (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm-package-arg\npa.js:79:12)
    at _install (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:62:11)

------------------

$ npm install element-plus --save
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\0\AppData\Local\npm-cache\_logs\2022-08-30T14_17_38_814Z-debug-0.log

    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:50:10)
    at toPromise (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:118:63)
    at next (C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:99:29)
npminstall version: 3.27.0
npminstall args: E:\Program Files\nodejs\node.exe C:\Users\0\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\0\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org element-plus --save

### What is Expected?

正常

### What is actually happening?

错误

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
Hello，这个应该是你环境问题，所以我将关闭这个issue。
你可以尝试以下操作：
删除lock文件，更换镜像源，淘宝旧的镜像源已经下架。
